name       : xorg-driver-video-intel
version    : 2.99.917
release    : 25
source     :
    - https://git.solus-project.com/projects/xf86-video-intel/snapshot/xf86-video-intel-8f33f80100096f7790c7b819ce37a3ed8ce8b5fa.tar.bz2 : 8e3cc35d19fcc2f4b249d38d2252c7717dcbe10cd345bca9d9e6e5927d51b730
license    :
    - MIT
summary    : Intel Video Driver
component  : xorg.driver
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(xvmc)
    - pkgconfig(xv)
    - pkgconfig(xcb)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(presentproto)
    - pkgconfig(dri3proto)
    - pkgconfig(xcb-aux)
    - pkgconfig(xfont)
    - pkgconfig(xorg-macros)
optimize   : no-bind-now
libsplit   : no
description: |
    The Xorg Intel Driver package contains the X.Org Video Driver for Intel integrated video cards including 8xx, 9xx, Gxx, Qxx and HD graphics processors (SandyBridge, IvyBridge and Haswell).
setup      : |
    %reconfigure --with-default-accel=sna \
               --enable-uxa \
               --enable-dri3 \
               --with-default-dri=3
build      : |
    %make
install    : |
    %make_install
