name       : xorg-driver-video-intel
version    : 2.99.917
release    : 41
source     :
    - git|https://gitlab.freedesktop.org/xorg/driver/xf86-video-intel.git : 25c9a2fcc83ae7252a178b42262da383e59df744
license    : MIT
component  : xorg.driver
summary    : Intel Video Driver
description: |
    The Xorg Intel Driver package contains the X.Org Video Driver for Intel integrated video cards including 8xx, 9xx, Gxx, Qxx and HD graphics processors (SandyBridge, IvyBridge and Haswell).
optimize   :
    - no-bind-now
    - no-symbolic
libsplit   : no
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(xfont2)
    - pkgconfig(xvmc)
    - pkgconfig(xv)
    - pkgconfig(xcb)
    - pkgconfig(xproto)
    - pkgconfig(xcb-aux)
    - pkgconfig(xorg-macros)
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %reconfigure --with-default-accel=sna \
               --enable-uxa \
               --enable-dri3 \
               --with-default-dri=3 \
               CFLAGS="$CFLAGS -O3"
build      : |
    %make
install    : |
    %make_install
