name       : xorg-driver-video-intel
version    : 2.99.917
release    : 32
source     :
    - git|git://anongit.freedesktop.org/xorg/driver/xf86-video-intel : 291fdcdc09420d8e422617070731eb3da3d55b44
license    :
    - MIT
summary    : Intel Video Driver
component  : xorg.driver
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(xfont2)
    - pkgconfig(xvmc)
    - pkgconfig(xv)
    - pkgconfig(xcb)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(presentproto)
    - pkgconfig(dri3proto)
    - pkgconfig(xcb-aux)
    - pkgconfig(xfont)
    - pkgconfig(xorg-macros)
optimize   : no-bind-now
libsplit   : no
description: |
    The Xorg Intel Driver package contains the X.Org Video Driver for Intel integrated video cards including 8xx, 9xx, Gxx, Qxx and HD graphics processors (SandyBridge, IvyBridge and Haswell).
setup      : |
    %reconfigure --with-default-accel=sna \
               --enable-uxa \
               --enable-dri3 \
               --with-default-dri=3 \
               CFLAGS="$CFLAGS -O3"
build      : |
    %make
install    : |
    %make_install
